(load "dict")
(load "patterns")

(define (match pat exp dict)
  (define (extend-dict pat exp dict)
    (if (dict-has? pat dict)
        (if (equal? (dict-lookup pat dict))
          dict
          'failed)
        (dict-add (pattern-variable pat) exp dict)))
  (cond ((eq? dict 'failed) 'failed)
        ((atom? pat)
          (if (and (atom? exp) (eq? exp pat))
              dict
              'failed))
        ((constant-pattern? pat)
          (if (constant? exp)
              (extend-dict pat exp dict)
              'failed))
        ((variable-pattern? pat)
          (if (variable? exp)
              (extend-dict pat exp dict)
              'failed))
        ((arbitrary-pattern? pat)
          (extend-dict pat exp dict))
        ((atom? exp) 'failed)
        (else
          (match (cdr pat)
                 (cdr exp)
                 (match (car pat) (car exp) dict)))))
